#es:
#  uris: localhost
#  port: 9200
#  username: elastic
#  password: JShfI-3you=Nq5gQxE2k
#  schemeName: https
#  ca: 12cca06a48a6d19388ae055bc5650dab612b5e91401f2322d6542a577491d211

# 사무실
#es:
#  host:  192.168.210.52
#  port: 9200
#  username: elastic
#  password: =dq2XKtp_p2DF_2QiLys
#  schemeName: https
#  ssl: fingerprint        # pwd, fingerprint, ca
#  fingerprint: 190f95778c4f9b2d5247d940b9665c3494b6f930914796cc4274c432150440a7
#  cadrt: C:\PRJ\hybird\elk


# 사무실 8.7.1
#es:
#  host:  192.168.210.52
#  port: 9200
#  username: elastic
#  password: GlFAJO2I=**kk8hjP02g
#  schemeName: https
#  ssl: fingerprint        # pwd, fingerprint, ca
#  fingerprint: 3b4a60ca061ab6a2c9d6289e768bd5a16de824a8126ca51bf8d8454756e8081b
#  cadrt: C:\PRJ\hybird\elk

# 개인
#es:
#  host:  172.31.25.224
#  port: 9200
#  username: elastic
#  password: =5k2f8LXRrA69xLk_LgU
#  schemeName: https
#  ssl: fingerprint        # pwd, fingerprint, ca
#  fingerprint: 1f27354472efc0b8c064883a7b26e23274f8479e99dfcf358625527a59c41b94
#  cadrt: D:\PRJ\hybird\elk

# 홈 8.9.0
#es:
#  host: 172.19.164.132
#  port: 9200
#  username: elastic
#  password: ji_DrcMq5xL+aCs+6VjO
#  schemeName: https
#  ssl: fingerprint        # pwd, fingerprint, ca
#  fingerprint: 8ff2a69c78554e2fbc80baa50742fe10de86583b13df24efd4c7f191f804fada
#  cadrt: D:\STUDY\SPRINGBOOT\hybird\elk\http_ca.crt

# 홈 8.7.1
#es:
#  host: 172.19.164.132
#  port: 9200
#  username: elastic
#  password: 1n=eBasM2jGx1EZF07DY
#  schemeName: https
#  ssl: fingerprint        # pwd, fingerprint, ca
#  fingerprint: 3f96bceb356611a7e6d660f4501f91ea3d13ebd732022c961b0cdda5f2d31f00
#  cadrt: D:\STUDY\SPRINGBOOT\hybird\elk\http_ca.crt

# badel mac
es:
  host: localhost
  port: 9200
  username: elastic
  password: 3JC+ju1pAFt2ab9p2+_V
  schemeName: https
  ssl: fingerprint
  fingerprint: ab83ac099f304b0397f81a21ca6496d73b6ec27cf8b5d415b1050ad850eca84e
  cadrt: /Users/ramachell/Documents/teamproject/travel_again/dockerfile/backend/elk/http_ca.crt

# hwang mac
#es:
#  host: localhost
#  port: 9200
#  username: elastic
#  password: 3JC+ju1pAFt2ab9p2+_V
#  schemeName: https
#  ssl: fingerprint
#  fingerprint: ab83ac099f304b0397f81a21ca6496d73b6ec27cf8b5d415b1050ad850eca84e
#  cadrt: /Users/ramachell/Documents/teamproject/travel_again/dockerfile/backend/elk/http_ca.crt


#doc:
#  demoIndex: demo
#  articleIndex: article
